PREFIX lto: <http://bp4mc2.org/lto#>

SELECT ?organisation ?naam ?contactinformatie
WHERE {
  BIND(<$_ORG_ID> AS ?organisation)
  ?organisation a lto:Organisatie .

  OPTIONAL { ?organisation lto:naamOrganisatie ?naam . }
  OPTIONAL { ?organisation lto:contactinformatie ?contactinformatie . }
    }
ORDER BY LCASE(STR(COALESCE(?naam, "")))